### ISSUE TITLE
Return value Error

### ISSUE THREAD

**Issue by adamiss5138** [iTXTech/SynapsePM#1]
Steps to reproduce the issue

1. Starting server
2. Plugin show error and doesn't load

Genisys: #2140
PHP: 7.0.11
Server OS: Windows
Game version: 0.16.0.5

`
[Server thread/INFO]: Enabling SynapsePM v1.0.0

[Server thread/CRITICAL]: TypeError: "Return value of synapse\Synapse::isMainServer() must be of the type boolean, null returned" (EXCEPTION) in "/src/synapse/Synapse" at line 164

[Server thread/INFO]: Disabling SynapsePM v1.0.0 `

**Comment by MichaelM04** [comment]
This looks like a mixup,  your using Genisys with Synapse built into the code, and the plugin is using the same file names/directory's. I'm going to start fully testing this and collaborate if allowed, I like the idea of this project

**Comment by DaMatrix** [comment]
@adamiss5138 this plugin runs on the fork from Tarik02, not the main one (yet). iTXTech's repo still has Synpase built-in (for now).

**Comment by adamiss5138** [comment]
@DaMatrix Genisys has SPP version 6 built in. I need SPP version 7 to work with 0.16 Nemisys

**Comment by DaMatrix** [comment]
exactly. my point is, the main genisys still has Synapse in it. This plugin conflicts with the synapse built in to Genisys. if you want to use this plugin you either have to use pocketmine or https://github.com/Tarik02/Genisys (which will be merged into Genisys. see https://github.com/iTXTech/Genisys/pull/2138)

**Comment by tarik02** [comment]
@adamiss5138, this plugin is incompatible with Genisys master branch. Please, use this fork [Genisys](https://github.com/iTXTech/Genisys/pull/2138). This will be merged soon.
