### ISSUE TITLE
[Server thread/INFO]: Enabling SynapsePM v1.0.3  Warning: Invalid argument supplied for foreach() in /home/mcpe/main/plugins/SynapsePM-master/src/synapsepm/SynapsePM.php on line 74

### ISSUE THREAD

**Issue by Erkam246** [iTXTech/SynapsePM#11]

**Comment by ishitatsuyuki** [comment]
Do not place too much garbage in the title.

The answer is: you haven't configured it.

**Comment by Erkam246** [comment]
How work this plugin can you make an tutorial in wiki?

**Comment by ishitatsuyuki** [comment]
**Stop spamming here and go to chats.** You're subject to a ban if you continue to abuse the issue tracker.

**Comment by Erkam246** [comment]
ok...
