### ISSUE TITLE
Bugs / Needs fixing's

### ISSUE THREAD

**Issue by ICrashHD** [iTXTech/SynapsePM#14]
**Description**

If "Use loading screen" is set to false, after you transferred to a server. The server freezes
But, if the "use loading screen" is set to true, everything works.

Also,

If set "loading screen" is true. After you transferred to another server, everything works fine. But when you teleport to another world, the server freezes

**How can i re-create this?**

Issue 1

Set "use loading screen" to false in config
Transferred to another server and watch it freezes
Issue 2

Set "use loading screern" to true in config
Transferred to another server, then there teleport to another word and watch it freezes server
Other information

I tried to add as much details as i can, instead of just adding a simple description, I've added a format that i made, which makes it more easy for you guys to read, and also parse it.

**Comment by Tarik02** [comment]
I'm can't reproduce it. All works fine for me.

**Comment by ICrashHD** [comment]
Put loading screen off in MAIN server. But it  "on"   on the server your trasfering to 

and then trasfer and then teleport to a world on the other server and you"ll see the server freeze!

**Comment by Tarik02** [comment]
@ICrashHD, `loading-screen` must be `on` in all server or `off` on all servers. And this freezes client, not server.

**Comment by ICrashHD** [comment]
Turn loading screen on, on all servers.


Goto a server, and now teleport to a world and watch the server freezes

Okay now for second bug..

Turn loading screen off, and you"ll freeze if you goto another server and you cant move

**Comment by Tarik02** [comment]
@ICrashHD, i can't reproduce this issue. I teleport between server hungred times, but this not happens.

**Comment by ICrashHD** [comment]
@Tarik02 

I"ll explain:

Put "loadingScreen: true" in main server and other servers

Trasfer to a server, after it's done. Teleport to any worlds, and watch the client freezes and also the server

**Comment by ICrashHD** [comment]
And when loadingScreen is off

On all servers, main etc. After teleporting to another server, you can't teleport to any worlds or the server will freeze!

**Comment by ICrashHD** [comment]
My method:

Remove loading screen, its useless if it's causing alot of bugs, etc. 

Otherwise, try to fix em!

**Comment by Tarik02** [comment]
@ICrashHD, too many bugs in client to fix it. Nobody knows right way to use it.

**Comment by ICrashHD** [comment]
Did some packet changes, works fine.....

Better to try to fix it, then ask for someone that doesn't know what they are doing or gives excuses :P
