### ISSUE TITLE
Need Help

### ISSUE THREAD

**Issue by ghost** [iTXTech/SynapsePM#15]
Hello,
Can i have more informations about how to install it ?
I already install SynapsePM on my main server and I restart it, the config of Synapse has been created, what i have to do next to connect this server to an other and why i can't join my server since i put Synapse on ?

**Comment by ishitatsuyuki** [comment]
No question here. You will be banned if you continue to abuse the issue tracker.

**Comment by ghost** [comment]
Can you just explain me how to use it ? @ishitatsuyuki @gaoyichuan

**Comment by ishitatsuyuki** [comment]
Okay, let me explain how you just get banned.
