### ISSUE TITLE
Pls Help !!!

### ISSUE THREAD

**Issue by ACAPlayer** [iTXTech/SynapsePM#16]
Can someone explain to me how I use _**the plugin**_ and _**connect with the server_**

Thank you in advance for your response

**Comment by DaMatrix** [comment]
I am predicting the future: one of the devs is going to close and lock this issue. If you can't figure out a plugin this simple,  you shouldn't be running a server.

**Comment by ishitatsuyuki** [comment]
Shut up idiot, the issue tracker is not your playground.

**Comment by DaMatrix** [comment]
welp, I called that

**Comment by buchwasa** [comment]
@ishitatsuyuki Do you honestly have to be that rude to the people that use Genisys and don't know what they are doing? Everyone needs a little help sometimes and it can be stupid help but you don't need to be a dick about it. Not everyone starts out knowing 100% what they need to do, most people start out not knowing what they are doing, and you aren't helping them get where they need to go.

**Comment by ishitatsuyuki** [comment]
GitHub is the developers' community, not the noob's.

**Comment by buchwasa** [comment]
@ishitatsuyuki And most come to GitHub to download it, so not everyone comes to code, many come and open issue requests because it's a community for developers and most are friendly enough to help them out.

**Comment by ishitatsuyuki** [comment]
I don't respond to anything that isn't an issue or feature request, that's all.

**Comment by buchwasa** [comment]
@ishitatsuyuki Be a little kinder with the wording, you don't call someone who doesn't know what they are doing an idiot.
