### ISSUE TITLE
Issue with connection at nemisys

### ISSUE THREAD

**Issue by asyncthreading** [iTXTech/SynapsePM#17]
i m using nemisys for synapse. Configured nemisys corectly, before i put the plugin "SynapsePM" on plugins folder, i configured again the config for SynapsePM and when i m starting the server it doesnt connect to synapse. How can i fix this

**Comment by asyncthreading** [comment]
And i am getting this error. 

[15:13:37] [Server thread/INFO]: Enabling SynapsePM v1.0.3

Warning: Invalid argument supplied for foreach() in phar:///home/hub/plugins/SynapsePM_v1.0.3.phar/src/synapsepm/SynapsePM.php on line 74

Notice: Undefined variable: synapseConfig in phar:///home/hub/plugins/SynapsePM_v1.0.3.phar/src/synapsepm/SynapsePM.php on line 76

**Comment by tarik02** [comment]
Give me your config.

**Comment by asyncthreading** [comment]
SynapsePM config:

enabled: true
disable-rak: false
synapses:

# \- enabled: true

# server-ip: 127.0.0.1

# server-port: 19132

# is-main-server: true

# server-password: mrnsinapsa

# description: "Hub"

loadingScreen: true

Nemisys Config:
#Properties Config file
#2016-11-16 10:02:02
motd=&7« &5Champions NetWork&7 »
server-port=19132
synapse-port=19132
password=mrnsinapsa
lang=eng
async-workers=auto
enable-profiling=off
profile-report-trigger=20
server-ip=0.0.0.0
max-players=100
plus-one-max-count=off
dynamic-player-count=off
enable-query=on
enable-rcon=off
rcon.password=1MjBmYzUyM
debug=1

**Comment by tarik02** [comment]
Hey, use markdown, your config is not readable!

**Comment by asyncthreading** [comment]
Explain me how to use it, and how. To get it

**Comment by ishitatsuyuki** [comment]
Wow! Such a great site! google.com

**Comment by asyncthreading** [comment]
Fixed it.
