### ISSUE TITLE
How do you set this up?

### ISSUE THREAD

**Issue by DaPigGuy** [iTXTech/SynapsePM#25]
I did what the README.md says on both my servers but I keep getting this:
[16:20:07] [SynapseClient thread/NOTICE]: Trying to re-connect to Synapse Server
[16:20:28] [SynapseClient thread/CRITICAL]: Synapse Client can't connect **.***.**.***:19134
[16:20:28] [SynapseClient thread/ERROR]: Socket error: A connection attempt failed because the connected party did not properly respond after a period of time, or established connection failed because connected host has failed to respond.

**Comment by DaPigGuy** [comment]
My config for server 1
enabled: true
disable-rak: false
synapses:
 - enabled: true
   server-ip: **.***.**.***
   server-port: 19132
   is-main-server: false
   server-password: 7a57a5a743894a0e
   description: "1"
   verbose-logging: false
loadingScreen: false

My config for server 2
enabled: true
disable-rak: false
synapses:
 - enabled: true
   server-ip: **.***.**.***
   server-port: 19134
   is-main-server: false
   server-password: 7a57a5a743894a0e
   description: "2"
   verbose-logging: false
loadingScreen: false

**Comment by DaPigGuy** [comment]
Genisys YML for server 1
synapse:
 #If you want to use Synapse API or connect to a synapse server, enable this
 enabled: true
 server-ip: **.***.**.***
 server-port: 19134
 #If this client is the lobby or the main server
 is-main-server: false
 server-password: 7a57a5a743894a0e
 #Description of this client is the identifier of this client
 description: "2"
 #Disable RakLib means that players can only join via Synapse
 disable-rak: false

Genisys YML for server 2
 synapse:
 #If you want to use Synapse API or connect to a synapse server, enable this
 enabled: true
 server-ip: **.***.**.***
 server-port: 19132
 #If this client is the lobby or the main server
 is-main-server: false
 server-password: 7a57a5a743894a0e
 #Description of this client is the identifier of this client
 description: "1"
 #Disable RakLib means that players can only join via Synapse
 disable-rak: false

**Comment by ishitatsuyuki** [comment]
And you didn't setup a frontend?
