### ISSUE TITLE
How can I find the description of the current server?

### ISSUE THREAD

**Issue by Henning-Klatt** [iTXTech/SynapsePM#29]
I have a second plugin next to SynapsePM, which works with mysqli and that should know how the current server (on which it runs) description is. Whats the best way to do this?

**Comment by SleepSpace9** [comment]
You could try this (untested):
```php
if($synapsepm = $this->getServer()->getPluginManager()->getPlugin('SynapsePM') !== null) {
	$descriptionFromConfig = $synapsepm->getConfig()->get('description');
	$descriptionFromMethod = $synapsepm->getSynapse()->getDescription();
}
```

**Comment by Henning-Klatt** [comment]
Thank you, 
on method from Config it will return this error:
`Elywing thread:CRITICAL > Error: "Call to a member function getConfig() on boolean" (EXCEPTION) in "/plugins/SlaveServer/src/SlaveServer/Main" at line 135`

on method fromMethod i have this error:
`Elywing thread:CRITICAL > Error: "Call to a member function getSynapse() on boolean" (EXCEPTION) in "/plugins/SlaveServer/src/SlaveServer/Main" at line 136`

But when i look at the config file, the description is in an array like format?!?

![bildschirmfoto 2016-12-29 um 12 11 46](https://cloud.githubusercontent.com/assets/12398950/21542707/04f76ca8-cdc0-11e6-80a1-57a5df866218.png)

**Comment by Henning-Klatt** [comment]
I found a solution:
You must set $synapsepm again, after the if:
`if($synapsepm = $this->getServer()->getPluginManager()->getPlugin("SynapsePM") !== null) {
            $synapsepm = $this->getServer()->getPluginManager()->getPlugin("SynapsePM");
            $this->description = $synapsepm->getSynapse()->getDescription();
        }`
