### ISSUE TITLE
Return value of synapse\Synapse::isMainServer()

### ISSUE THREAD

**Issue by ghost** [iTXTech/SynapsePM#30]
>  CRITICAL> TypeError: "Return value of synapse\Synapse::isMainServer() must be of the type boolean, null returned" (EXCEPTION) in "/src/synapse/Synapse" at line 164

At start up

**Comment by SleepSpace9** [comment]
Check your config.yml in SynapsePM plugin folder, I guess the line ```   is-main-server: ``` is commented out or has an invalid value or maybe the yaml format is invalid.

Possible values:
```  is-main-server: true``` 
or
```  is-main-server: false```

**Comment by ghost** [comment]
@SleepSpace9 No, I've set it up. `is-main-server: true`  
And the file did not have any problem.

**Comment by SleepSpace9** [comment]
If you use Genisys, did you update your genisys.yml to the latest version so that there are no Synapse entries in it?

**Comment by ghost** [comment]
I using Tesseract and Synapse-PM...
Is there a possibility of src problem?

**Comment by dktapps** [comment]
Most likely.

**Comment by ghost** [comment]
I'll try to use Genisys

**Comment by ghost** [comment]
I got the same error
> Notice: Undefined index: isMainServer in D:\PMMP\Genisys0.16\src\synapse\Synapse.php on line 76
Notice: Undefined index: password in D:\PMMP\Genisys0.16\src\synapse\Synapse.php on line 77
[22:29:54] [Server thread/CRITICAL]: TypeError: "Return value of synapse\Synapse::isMainServer() must be of the type boolean, null returned" (EXCEPTION) in "/src/synapse/Synapse" at line 164

**Comment by tarik02** [comment]
@fuyutsuki, it's problem with SynapsePM config. Post it here.

**Comment by ghost** [comment]
![default](https://cloud.githubusercontent.com/assets/16377174/21590687/5be3ebe8-d141-11e6-87e0-eff23ef76bb3.JPG)

hmm....?

**Comment by SleepSpace9** [comment]
Are you sure you are using the the latest SynapsePM? I ask because the line numbers of your error messages differ from this repository.

**Comment by ghost** [comment]
latest. I'll try again…

**Comment by tarik02** [comment]
@fuyutsuki, you use not latest version of Genisys. Update it to the latest and issue must be fixed.

**Comment by ghost** [comment]
It was solved by reinstalling Genisys.
thank you!
