### ISSUE TITLE
commands do not work

### ISSUE THREAD

**Issue by vzlomka76** [iTXTech/SynapsePM#31]
I teleport to another server using SynapsePM, the commands are taken from the server from which I teleported (from the hub). If I manually entered IP and port of the game, the commands will work normally

PHP: 7.06
Core: Elywing

Steps to reprocude:
1. Download synapsepm to your server
2. Teleport to another server with synapsepm
3. commands taken from the hub

**Comment by MichaelM04** [comment]
I wouldn't be using Elywing, it has many issues. But your software isn't the issue in this case, this issue happens to me as well using the latest build of PocketMine-MP from branch: MCPE-1.0, and the latest SynapsePM build. If you use a manual command dispatcher on the server you transfered to the command will work fine, only doesn't work when the client runs the command normally. Just need to send the client the new command data.

**Comment by vzlomka76** [comment]
@MichaelM04 in pmmp my worlds don't work, they incorrectly load
![2017-01-01 20-06-11](https://cloud.githubusercontent.com/assets/16573760/21582151/ca2a5496-d05d-11e6-9b23-45253861304a.png)

**Comment by MichaelM04** [comment]
@vzlomka76 My new PR should fix this issue. If you would test this to second it, that would be great. #32

**Comment by vzlomka76** [comment]
@MichaelM04 It's work!!! Nice, thank you

**Comment by JackboyPlay** [comment]
I use Nukkit and the Commands are working
