### ISSUE TITLE
Synapse Protocol has been updated to version 8, please update.

### ISSUE THREAD

**Issue by boybook** [iTXTech/SynapsePM#34]
Synapse Protocol has been updated to version 8. I used new Header for packets, it will be more reliable. About the new header, you can see https://github.com/iTXTech/Nemisys/blob/master/src/main/java/org/itxtech/nemisys/network/synlib/SynapseProtocolHeader.java

**Comment by boybook** [comment]
Encoder: https://github.com/iTXTech/Nemisys/blob/master/src/main/java/org/itxtech/nemisys/network/synlib/SynapsePacketEncoder.java
Decoder: https://github.com/iTXTech/Nemisys/blob/master/src/main/java/org/itxtech/nemisys/network/synlib/SynapsePacketDecoder.java

**Comment by tarik02** [comment]
If anybody want to get update - do it yourself and make a pull request. I was abandoned minecraft and i don't want to waste time for it.

**Comment by NyaomiDEV** [comment]
This is awful. I mean, there's a server proxy that can be a lot powerful but no official support for pocketmine (that is the most used core for mcpe) anymore. Seriously guys? Are you really wasting this project this way?
By the way now how can someone write spp 8 changes into SynapsePM? @boybook I think you should give more than those links: where and when are those classes called?

**Comment by tarik02** [comment]
#45
