### ISSUE TITLE
Get plugin of another synapse server.

### ISSUE THREAD

**Issue by Ragnok123** [iTXTech/SynapsePM#36]
Hello. I have 2 test servers, first is lobby, second is minigame server.
I want when player touch npc, while minigame on second server is running, it doesnt teleport him to 2nd server, but writes message.
But how I can use minigame function on lobby server? How i can get plugin from minigame server on lobby server?

**Comment by tarik02** [comment]
You must to write your own thing to connect servers, for example you can use MySQL server. This is not issue of SynapsePM.
