### ISSUE TITLE
get all Server-Instances

### ISSUE THREAD

**Issue by Bluplayz** [iTXTech/SynapsePM#40]
i make a plugin for Tesseract and want to make a function which returns me all Servers as "Genisys-Server" instance so that i can get all informations and add something... hope any one can help me

**Comment by Bluplayz** [comment]
lol can you tell me why you closed it? i only ask normally lol

**Comment by tarik02** [comment]
Because issues are not questions.

**Comment by Bluplayz** [comment]
ty, but where can i ask my question?
