### ISSUE TITLE
what code i need?!

### ISSUE THREAD

**Issue by StephanToGo** [iTXTech/SynapsePM#5]
i love your work, really!!!
but i cant write down a plugin that can transfer player...
i didnt find the right using of synapse.
can someone help? i missed something maybe...

have someone more infos as
$this->getServer()->getPluginManager()->getPlugin('SynapsePM')->getSynapses();
it doesnt work to get the ways...

ps. all runs fine, synapse server and my lobby server is connected. but cant tranfer a player from lobby to another server because i dont know how xD

**Comment by tarik02** [comment]
Hello. Your solution:

```
// Transfer $player
foreach ($player->getSynapse()->getClientData() as $hash => $cdata)
{
    if ($cdata["description"] == 'lobby') // to lobby
    {
        $player->transfer($hash);
        break;
    }
}
```

**Comment by NyaomiDEV** [comment]
can $player be a pocketmine\Player instance or we need an instance of synapse\Player?
If so, how can we get that instance? I'm getting mad.

**Comment by xZeroMCPE** [comment]
pocketmine\Player

doesnt really matter.......

**Comment by iPocket** [comment]
no.
synpase\Player
where the getSynapse() method

**Comment by xZeroMCPE** [comment]
@iPocket 

I used pocketmine\Player, and it still worked for me. No matter which one is being used.

**Comment by NyaomiDEV** [comment]
@iPocket how to get synapse\Player instance if there isn't a getSynapsePlayer($player) function in SynapsePM's Main class?

**Comment by tarik02** [comment]
@AryToNeX synapse\Player is extended from pocketmine\Player. So, if $player instanceof \synapse\Player is true, then $player instanceof \pocketmine\Player is also true.

**Comment by xZeroMCPE** [comment]
@Tarik02 That's mostly what i was trying to them tell....

But @iPocket got it all wrong....
