### ISSUE TITLE
[Request] | SteadFast Compatibiliy

### ISSUE THREAD

**Issue by Guillaume351** [iTXTech/SynapsePM#6]
Hello,
If you start this plugin on SteadFast, you'll get  :
>[13:33:12] [Server thread/INFO]: Enabling SynapsePM v1.0.0

>Fatal error: Uncaught Exception: Serialization of 'Closure' is not allowed in [no active file]:0
>Stack trace:
>#0 {main}
>  thrown in [no active file] on line 0
>bin\php\php.exe: Exit 127

I would like to know if you could update it to make it compatible with SteadFast, or if Genisys / Steadfast are too different to make a plugin-side fix.

Thanks

**Comment by tarik02** [comment]
SteadFast2 has other structure than PocketMine or Genisys, so SynapsePM will not support SteadFast2 for now.

**Comment by Guillaume351** [comment]
@Tarik02 Some progress :  in SynapseClient.php, I commented some line of the run() function.
`

>   public function run(){
>       $this->registerClassLoader();
>       gc_enable();
>       error_reporting(-1);
>       /*
>       ini_set("display_errors", 1);
>       ini_set("display_startup_errors", 1);
> 
> ```
>   set_error_handler([$this, "errorHandler"], E_ALL);
>   register_shutdown_function([$this, "shutdownHandler"]);
> ```
> 
> */
>       try{
>           $socket = new SynapseSocket($this->getLogger(), $this->port, $this->interface);
>           new ServerConnection($this, $socket);
>       }catch(\Throwable $e){
>           $this->logger->logException($e);
>       }
>   }
> `

Now I no longer have crash for this reason. But to be compatible with SteadFast, the player file need to be updated (the processLogin() function does not exist on SteadFast)

Edit : in redirect packet, you have to change unsignedvarint() by varint() (different function names) annnd spawns !

**Comment by tarik02** [comment]
Too very many problems here. You may create your own fork and make compatible SynapsePM for SteadFast.

**Comment by ghost** [comment]
Just asking, have you made any progress yet?

**Comment by tarik02** [comment]
@MyNameIsTriXz, no. I abandoned minecraft.

**Comment by ghost** [comment]
Oh, that's sad to hear. :/ I hope this project won't get abandoned too

**Comment by tarik02** [comment]
@MyNameIsTriXz, I will do something in free time, if thia will needed.

**Comment by ghost** [comment]
Oh oke

**Comment by vzlomka76** [comment]
@Tarik02 We have fork of SynapsePM for steadfast2, but we have a problem, the players how to move, as it were, no. https://github.com/WoodCraftMC/SynapsePM. Video: http://radikal.ru/video/NtRG6DrIvcH.
I hope you can help :), we have fork of steadfast2, we are doing tests on it: https://github.com/WoodCraftMC/SpeedMine

**Comment by Guillaume351** [comment]
@vzlomka76 Steadfast sends packets differently, they use a system with "identifiers" (attributed in RaklibInterface when a player join), so there is a lot of changes to be done to make it work
